# Generated by Django 4.2.6 on 2023-11-05 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='learningPath',
            fields=[
                ('idlearningPath', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('professionalRole', models.CharField(max_length=45)),
                ('pathScore', models.FloatField()),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('idTags', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('idLearningPath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningPath.learningpath')),
            ],
        ),
        migrations.CreateModel(
            name='skillLearningPath',
            fields=[
                ('idSkills', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('idLearningPath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningPath.learningpath')),
            ],
        ),
    ]
