# Generated by Django 4.2.6 on 2023-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_course_idcourse_course_id_and_more'),
        ('learningPath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllearningpath',
            name='idLearningPath',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='idLearningPath',
        ),
        migrations.AddField(
            model_name='learningpath',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='skill',
            field=models.ManyToManyField(to='learningPath.skilllearningpath'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='tag',
            field=models.ManyToManyField(to='learningPath.tags'),
        ),
    ]
