# Generated by Django 4.2.6 on 2023-11-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_review_idcourse_remove_review_idstudent_and_more'),
        ('learningPath', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllearningpath',
            name='idLearningPath',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='idLearningPath',
        ),
        migrations.DeleteModel(
            name='learningPath',
        ),
        migrations.DeleteModel(
            name='skillLearningPath',
        ),
        migrations.DeleteModel(
            name='tags',
        ),
    ]
