# Generated by Django 4.2.6 on 2023-11-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institution',
            fields=[
                ('institutionCode', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
