# Generated by Django 4.2.6 on 2023-11-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_delete_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='institution',
            fields=[
                ('idInstitution', models.AutoField(primary_key=True, serialize=False)),
                ('institutionCode', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
