# Generated by Django 4.2.6 on 2023-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('intermediate', 'intermediate'), ('difficult', 'difficult')], max_length=100),
        ),
    ]
