# Generated by Django 4.2.6 on 2023-11-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interest',
            fields=[
                ('idInterest', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='skillStudent',
            fields=[
                ('idSkillStudent', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('idStudent', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=45)),
                ('interest', models.ManyToManyField(to='student.interest')),
                ('skill', models.ManyToManyField(to='student.skillstudent')),
            ],
        ),
    ]
