# Generated by Django 4.2.6 on 2023-11-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='idStudent',
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='idStudent',
        ),
        migrations.AddField(
            model_name='student',
            name='interest',
            field=models.ManyToManyField(to='student.interest'),
        ),
        migrations.AddField(
            model_name='student',
            name='skill',
            field=models.ManyToManyField(to='student.skillstudent'),
        ),
        migrations.DeleteModel(
            name='petition',
        ),
    ]
