# Generated by Django 4.2.6 on 2023-11-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningPath', '0002_remove_skilllearningpath_idlearningpath_and_more'),
        ('course', '0002_remove_review_idcourse_remove_review_idstudent_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='idStudent',
        ),
        migrations.RemoveField(
            model_name='skillstudent',
            name='idStudent',
        ),
        migrations.DeleteModel(
            name='interest',
        ),
        migrations.DeleteModel(
            name='petition',
        ),
        migrations.DeleteModel(
            name='skillStudent',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
